spring:
  application:
    name: qhstore-api

  profiles:
    active: dev

  # Database Engine Connection (PostgreSQL)
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  # JPA & Hibernate Configurations
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.jdbc.batch_size: 20
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true

  # File Upload Matrix (Multipart Configurations)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Server Port Network Matrix
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Custom Security & App Parameters (Extracted into .env)
app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-ms: ${JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}
  security:
    pepper: ${APP_SECURITY_PEPPER}

logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        engine:
          jdbc:
            batch:
              internal:
                BatchingBatch: TRACE
      springframework:
        security:
          config:
            annotation:
              authentication:
                configuration:
                  InitializeUserDetailsBeanManagerConfigurer: ERROR

# Cloudinary Storage Configuration Matrix
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# PayOS Configuration Matrix
payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: ${PAYOS_RETURN_URL}
  cancel-url: ${PAYOS_CANCEL_URL}